substitutions:
  name: athom-smart-plug
  friendly_name: "Athom Smart Plug"
packages:
  athom.smart-plug: github://athom-tech/athom-configs/athom-smart-plug.yaml
esphome:
  name_add_mac_suffix: false
  includes:
    - espsense.h
  libraries:
    - "ESPAsyncUDP"
    
custom_component:
- lambda: |-
    auto sense_device = new ESPSense();
    auto sense_plug = new ESPSensePlug();
    
    sense_plug->set_name("${friendly_name}");
    sense_plug->set_power_sensor(id(socket_my_power));
    
    sense_device->addPlug(sense_plug);
    return {sense_device};

ota: 
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

